Console.WriteLine();
Console.WriteLine("Cidades do Litoral Sul");
Console.WriteLine();
Console.WriteLine("- Peruíbe");
Console.WriteLine("- Itanhaém");
Console.WriteLine("- Mongaguá");
Console.WriteLine("- Praia Grande");
Console.WriteLine("- São Vicente");
Console.WriteLine("- Santos");
Console.WriteLine("- Guarujá");
