Console.WriteLine("Preparar...");
Console.ReadKey();
Console.WriteLine("Apontar...");
Console.ReadKey();
Console.WriteLine(".");
Console.ReadKey();
Console.WriteLine("..");
Console.ReadKey();
Console.WriteLine("...");
Console.ReadKey();
Console.WriteLine("FOGO! (O_o)");
Console.ReadKey();
